---
- name: Provision for Ubuntu 16 and Python for Ansible
  hosts: vagrant2
  strategy: linear
  sudo: yes
  remote_user: root
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson

- name: This playbook sets up OJS infrastructure with Vagrant
  hosts: vagrant
  strategy: linear
  sudo: true
  sudo_user: root

  vars_files:
    - vars/default.yml

  roles:
    - locale
    - mysql
    - ojs
    - php
    - nginx

- name: This playbook sets up OJS infrastructure
  hosts: comertec
  sudo: true
  sudo_user: root

  vars_files:
    - vars/default.yml

  roles:
    - locale
    - mysql
    - ojs
    - php
    - nginx
