# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "gbarbieru/xenial"

    # Skip checking for an updated Vagrant box
    config.vm.box_check_update = false

    config.vm.hostname = "ojs"

    config.vm.network :public_network
    config.vm.network "private_network", ip: "192.168.100.100"
    config.vm.network :forwarded_port, guest: 80, host: 8000 # Apache
    config.vm.network :forwarded_port, guest: 3306, host: 3307 # MySQL

    config.vm.provision "fix-no-tty", type: "shell" do |s|
        s.privileged = false
        s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
    end

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.inventory_path = "hosts"
        ansible.sudo = true
        ansible.verbose = "vvvv"
    end

    config.vm.provider "virtualbox" do |v|
        # https://www.virtualbox.org/manual/ch08.html
        v.memory = 1024
        v.cpus = 1
        v.customize ["modifyvm", :id, "--pae", "on"]
        v.customize ["modifyvm", :id, "--hwvirtex", "on"]
        v.customize ["modifyvm", :id, "--nestedpaging", "on"]
    end

    shared_dir = "/vagrant"
end
