mysql_root_password: ojs
mysql_databases:
  - name: ojs_db
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: ojs_user
    host: "localhost"
    password: ojs
    priv: "ojs_db.*:ALL"

php_enable_apc: true
php_webserver_daemon: "nginx"
php_enable_php_fpm: true
php_fpm_listen: "127.0.0.1:9000"
php_fpm_listen_allowed_clients: "127.0.0.1"
php_fpm_pm_max_children: 50
php_fpm_pm_start_servers: 5
php_fpm_pm_min_spare_servers: 5
php_fpm_pm_max_spare_servers: 5
php_memory_limit: "128M"
php_max_execution_time: "90"
php_upload_max_filesize: "5M"
php_packages:
  - php
  - php-cli
  - php-common
  - php-dev
  - php-gd
  - php-mbstring
  - php-pdo
  - php-xml
  - php-mysql
  - php-apcu
  - php-curl
php_date_timezone: "America/Sao_Paulo"
#php_error_reporting: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
php_error_reporting: "E_ALL & ~E_DEPRECATED"
php_display_errors: "Off"
php_display_startup_errors: "On"

nginx_vhosts:
  - listen: "80"
    server_name: "ojs.comertec.org"
    root: "/var/www/ojs.comertec.org/public_html/"
    index: "index.php"
    access_log: "/var/www/ojs.comertec.org/logs/ojs_access.log"
    error_log: "/var/www/ojs.comertec.org/logs/ojs_error.log"
    extra_parameters: |
      location ~ \.php$ {
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass 127.0.0.1:9000;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include fastcgi_params;

          fastcgi_buffers 16 16k; 
          fastcgi_buffer_size 32k
      }
nginx_remove_default_vhost: true
nginx_worker_processes: "{{ ansible_processor_vcpus|default(ansible_processor_count) }}"
nginx_worker_connections: "1024"
nginx_multi_accept: "off"
nginx_client_max_body_size: "64m"

server_name: 192.168.100.100

locale: en_US.UTF-8
